### ISSUE TITLE
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms"

### ISSUE THREAD

**Issue by Bankde** [mazen160/jwt-pwn#6]
```
(base) jwt-pwn $ python3 jwt-mimicker.py "token_here"
Traceback (most recent call last):
  File "jwt-mimicker.py", line 33, in <module>
    main()
  File "jwt-mimicker.py", line 21, in main
    jwt_token_value = jwt.decode(jwt_token, verify=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/jwt/api_jwt.py", line 80, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```
This is because pyjwt has updated to 2.0 with many breaking changes.
https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#require-explicit-algorithms-in-jwtdecode-by-default

Fast solution:
`pip install pyJWT==1.7.1`

**Comment by mazen160** [comment]
Hi @Bankde 

I tried explicitly specifying the algorithm and set verification to `False`, but it's still disallowed because of the new restrictions.

I pushed an update to requirements.txt to pin version `1.7.1` for `pyJWT` - this should be suitable for the current time.

Thanks again for reporting!
